FROM ubuntu:18.04 AS builder

RUN apt-get update && \
apt-get install --yes make gcc g++

WORKDIR /opt

COPY . /opt/jsonnet

RUN cd jsonnet && \
    make

FROM ubuntu:18.04

COPY --from=builder /opt/jsonnet/jsonnet /usr/local/bin
COPY --from=builder /opt/jsonnet/jsonnetfmt /usr/local/bin

ENTRYPOINT ["/usr/local/bin/jsonnet"]
